### ISSUE TITLE
Fails to build on cordova-ios 4.0.1

### ISSUE THREAD

**Issue by drmartin1998** [Telerik-Verified-Plugins/Keychain#2]
When attempting to build an application that includes the Keychain plugin using Cordova iOS version 4.0.1 the following error is thrown:

 error: no visible @interface for
      'CDVPlugin' declares the selector 'initWithWebView:'
    self = (CDVKeychain_)[super initWithWebView:(UIWebView_)theWebView];

**Comment by okonon** [comment]
@EddyVerbruggen i am running into the same issue with this plugin. Here is my info:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.3 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68 

```

```
platforms/ios/Frockhub/Plugins/com.shazron.cordova.plugin.keychainutil/CDVKeychain.m:27:33: error: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
    self = (CDVKeychain*)[super initWithWebView:(UIWebView*)theWebView];
                          ~~~~~ ^~~~~~~~~~~~~~~
1 error generated.

```

**Comment by EddyVerbruggen** [comment]
Yeah cordova-ios-4 has moved some stuff around. Use cordova-ios-3.x until this is fixed please.

**Comment by okonon** [comment]
@EddyVerbruggen this fix works for me:
https://github.com/shazron/KeychainPlugin/pull/25

That pull request has been there months...

thanks
